### ISSUE TITLE
Documentation PDF is corrupted as of 3/10

### ISSUE THREAD

**Issue by kevjustice** [mzbotreprap/VORON#1]
Tried to view it but after about 5 pages it cuts in the middle (even viewing online within GIT).

**Comment by vonnieda** [comment]
@kevjustice May be your browser or reader. Working fine for me. I get 7 pages with a "Congrats" message at the end both in Chrome within Github and downloaded and opened in Preview.

**Comment by mzbotreprap** [comment]
Do you have the same issue when you "git clone" and open locally?

**Comment by kevjustice** [comment]
Maybe it's a browser/GIT issue.  When I download the entire zip it's fine.  But downloading just the pdf and Adobe won't even open it and in the GIT viewer it shows like the image attached.  At least I got it.
![gb1](https://cloud.githubusercontent.com/assets/7374411/13680529/f7db2068-e6c6-11e5-9450-0722f1623c85.jpg)
