### ISSUE TITLE
slight amount of play carriage 1.5

### ISSUE THREAD

**Issue by calagan57** [mzbotreprap/VORON#103]
Hi,
(sorry for my bad english)

I made X carriage v1.5 with IGUS bearing. I have "slight play" with this carriage....I can move  The nozzle (slightly) with my finger.... It seems it's my IGUS bearing but Have you got too this problem?

Thank you!

**Comment by Maglin** [comment]
This would be a printer calibration problem.  The 1.5 X carriage has been in use by many people.  Also, it's designed for LM8U's so IGUS bushing are not it's intended bearing.
