### ISSUE TITLE
M5x10 screws are too long

### ISSUE THREAD

**Issue by Kriechi** [mzbotreprap/VORON#104]
I just tried assembling my self-sourced VORON 1.5 - but had to stop early because the M5x10 screws to fix everything to the M5 T-nuts & 2020 profiles are too long. I can screw them tight until the screw hits the inside of the 2020 slot, but the printed part is still loose.

Either the printed parts are too thin, or the screws are too long. I'm going to get some M5x8mm, which should fit and provide a solid screw connection.

Is anybody else experiencing this issue?
Are there differences in the slot depth of the 2020 profiles? I got mine from SMT in Germany (6mm slot, S106B2020)

**Comment by Kriechi** [comment]
Apparently the 2020 profile from SMT have a shallower slot.
![slack-imgs](https://user-images.githubusercontent.com/114300/29995442-a8f9300c-8fe9-11e7-90cc-dea917cc8079.jpg)

Compared to the Misumi ones:
![pasted_image_at_2017_09_01_07_21_am_360](https://user-images.githubusercontent.com/114300/29995447-bd47705a-8fe9-11e7-9093-624b7c99df7e.png)

I will updated #102 to fix the BOM.

**Comment by pakerfeldt** [comment]
You are pasting the wrong SMT image. The depth of that profile is the same as misumi and the screws fits just fine.

**Comment by Kriechi** [comment]
Thanks! My mistake - I replaced the image above to avoid confusion.

**Comment by Kriechi** [comment]
Since most parts have a 4mm wall, I would argue that even the original Misumi profiles + M5x10 are not optimal, because the barely fit (4mm wall + 2mm profile wall + 4mm slot depth = 10mm screw length length).
