### ISSUE TITLE
Duet Bracket Hole Spacing

### ISSUE THREAD

**Issue by redblueboy** [mzbotreprap/VORON#128]
Regarding the Duet Bracket STL in the STLs/VORON2/Base Compartment folder

The hole spacing is currently 2mm too wide. Holes should be spaced 115mm on center. Current spacing in STL is 117mm on center.

Duet Mounting Guide:
[https://duet3d.dozuki.com/Wiki/Mounting_and_cooling_the_board](url)

Duet Bracket STL:
[https://github.com/mzbotreprap/VORON/blob/master/STLs/VORON2/Base%20Compartment/Duet%20Bracket%20-%20From%202020%20Extrusion%20x4%20(Use%20Metal%20Standoffs%20or%20Plastic%20Spacers).STL](url)

**Comment by Maglin** [comment]
Everyone with a Duet including myself has no issues with it.  2mm is a pretty big gap.

**Comment by Maglin** [comment]
The issue has been verified.  So far seems links to the Duet Clone boards.  Others might need to chime in.  Truckmonky is working on a possible fix.

**Comment by ubernero** [comment]
Tested printed bracket with my Fystec Duetwifi clone, no issues using motherboard standoffs

**Comment by Maglin** [comment]
Cleaning house.  This issue has been resolved.  Thank you.
