### ISSUE TITLE
VORON2 Draw

### ISSUE THREAD

**Issue by denisbrandao** [mzbotreprap/VORON#130]
Any chance of the VORON2 STEP or FUSION version? Or a BOM with extrusion dimensions? I am drawing before build it, but it is only guessing from the videos.

![voron2 v4](https://user-images.githubusercontent.com/4682966/38276305-f32aa876-376a-11e8-91a8-731df3df3219.png)

**Comment by andreq** [comment]
http://mzbot.us/v2_configurator

**Comment by Maglin** [comment]
The STEP files will come in time.
