### ISSUE TITLE
STEP files

### ISSUE THREAD

**Issue by quixotic120** [mzbotreprap/VORON#16]
hey

are you willing to share more step files? I wanted to edit the bed support carriage to work with a delrin anti-backlash leadscrew nut (like this http://qtecstore.com/pages/leadscrew_nuts/6mm_leadscrew_nuts/common/6mm_screwnutx2.jpg) because that's what I have on hand. will share it along with x midsection I'm making for the diamond hotend

thanks!

**Comment by mzbotreprap** [comment]
Of course. I think I actually have this already desinged actually. This was one of the parts I was testing.

Lemme dog though the revision history

**Comment by mzbotreprap** [comment]
s/dog/dig/

**Comment by quixotic120** [comment]
Thanks! I don't follow though. Is that in the rev history somewhere? I don't see it

on the diamond hotend part - i'll open another issue bc I don't want this thread to get confusing

**Comment by mzbotreprap** [comment]
Rev history is in my Fusion360 account :) There's a year worth of experiments in there, all the way back when I was just trying to design a better TAZ. Doesn't make sense to dump it all here though.

**Comment by quixotic120** [comment]
Ah! do you have it shared? I can dig through if so, fusion360 would actually be great for me

**Comment by mzbotreprap** [comment]
Added the STEP file for the bed carriage. I couldn't find the version for those blocks, sorry. In ether case, it would have been very out of date.

I don't have it shared, since it looks like a college dorm room. As a grown ass man, it's embarrassing to have that kind of mess exposed to the public :)

**Comment by porterble** [comment]
an ass man... oh dear :p

**Comment by quixotic120** [comment]
Understand not sharing the fusion360 acct - mine is also pretty awful.

Thanks for sharing the step though! Pretty busy this week but should have some time next week. If I get something working I will share it!
