### ISSUE TITLE
V2.1: Z axis pulley and top idler are note aligned

### ISSUE THREAD

**Issue by schlnk** [mzbotreprap/VORON#189]
Distance from the inner side of extrusion to the belt edge at the upper idler is: 5,4mm (idler frame) + 5mm (bearing holder) + 1mm (washer) + 7.5 mm (idler hub) = 18.9 mm. 

Distance from the inner side of extrusion to the belt edge at the bottom pulley is: 14mm (z-drive front support) + 1mm (washer) + 1 mm (pulley flange) = 16 mm.  

So the  the top idler and the pulley are off-axis 2.9 mm. They should be aligned (z-drive front support should be 2.9 mm thicker). 

As a temporary workaround I used modified z-drive front support STLs, which are 3 mm thicker than original ones. 

Discord discussion is [here](https://discordapp.com/channels/460117602945990666/461134007959289858/538471610727006212).

![image](https://user-images.githubusercontent.com/34524772/52196849-69ea7f00-286e-11e9-9c79-333a5f7a6ae5.png)
![image](https://user-images.githubusercontent.com/34524772/52196964-e8dfb780-286e-11e9-9c90-6beae37495d2.png)

**Comment by Maglin** [comment]
This has been addressed.  Thank you.
