### ISSUE TITLE
X Carriage Bearing length for single extruder setup

### ISSUE THREAD

**Issue by Fheilmann** [mzbotreprap/VORON#19]
Hi there,

I have a question about the X-carriage in single-extruder configuration. I printed the necessary parts, and it seems that, with only one extruder, the double length LM8LUU should be replaced by single length LM8UUs.

Is this correct? If so the BOM and manual don't reflect these things, yet.

Bests

Florian

**Comment by mzbotreprap** [comment]
Hey,

The X Carriage uses single heights LM8UUs regardless of the hot end configuration. That's the 2 in the BOM. The rest are used in the XY Joints and the Bed Carriages. You can check the manual for reference to what I'm talking about.

**Comment by Fheilmann** [comment]
Shoot. Sorry I completely missed that. Closed.
