### ISSUE TITLE
Voron 1.6 and up Fusion 360 or STEP files missing

### ISSUE THREAD

**Issue by galorin** [mzbotreprap/VORON#198]
The Voron 1.5 has STEP and f3d files which has allowed me to modify parts to suit my particular circumstances.  Are there plans to include the 1.6, and full 2.1 f3d/step files?

**Comment by volcom8190** [comment]
per discords faq: 

Q: Will cad source files be released?
A: No planned date on the released of cad files, step files, or anything other than the stls

**Comment by Maglin** [comment]
No STEPS!
