### ISSUE TITLE
Documentation: Greasing bearings

### ISSUE THREAD

**Issue by codexmas** [mzbotreprap/VORON#22]
As I am running through the build, I noted that the first occurrence of a bearing needing to be greased was on page 20. I would like to suggest that the greasing instructions be moved earlier in the docs into a preparatory section.

The flow once you start building would be much improved, as you get all the dirty messy bits done at once and not have to take a break to do them in the middle of assembly.

**Comment by mzbotreprap** [comment]
I like this. Are you in QA by any chance? Cause this is some quality QA 🤓

**Comment by porterble** [comment]
Would make sense to go with the section A.3. When i built mine i greased them all up at the start.

**Comment by codexmas** [comment]
Not in QA, but certainly a programmer. Having a ton of fun doing the mechanical and enjoying the process.
