### ISSUE TITLE
Documentation: Multiplication fail

### ISSUE THREAD

**Issue by codexmas** [mzbotreprap/VORON#23]
This is really my issue, but in all the excitement to print things out I never really thought about some of the part counts in the folders, and that the Z Tower folder also specifies (2x)

So, I will be printing another set of the upper and lower braces cause dumb :)

Maybe change the folder name to be just Z Tower and the part counts to be (4x)?

**Comment by porterble** [comment]
Haha, i did the same thing earlier, and so ill take the rap for having the x2 in both places, see an earlier closed ticket. Made sense to me at the time, but in hindsight the x4 notation would be more obvious.

**Comment by mzbotreprap** [comment]
I think I overthought this and went too inductive on the folders. Need to pull back into reality and flatten things out.

**Comment by dcousens** [comment]
@mzbotreprap that would be much preferred IMHO :+1:

**Comment by timmit99** [comment]
Maybe make a PDF of what printed parts are required with a rendering next to the name and the amounts needed.
