### ISSUE TITLE
Documentation: Belts

### ISSUE THREAD

**Issue by codexmas** [mzbotreprap/VORON#25]
Wanted to suggest that an approximate belt length be specified in the documentation.
The BOM only lists 3 meters, which once can assume means 1.5/belt.
I had a roll of GT2 already and cut quite a bit of extra length just incase.

**Comment by mzbotreprap** [comment]
This is an excellent idea

**Comment by dcousens** [comment]
@codexmas careful,  the belts not be of equal length IIRC

**Comment by mzbotreprap** [comment]
@dcousens how did you end up with belts that are not of equal length?

**Comment by dcousens** [comment]
@mzbotreprap you know,  that is a good question.   I'm basing this purely on the measurements from OpenSCAD which gives me;

```
ECHO: "GT2_path length:", 1371
ECHO: "GT2_path length:", 1375
```

I wonder where that 4mm comes from :smiley:
