### ISSUE TITLE
lead screw stabilization

### ISSUE THREAD

**Issue by quixotic120** [mzbotreprap/VORON#27]
do you have any issues with the top half of the lead screw being free to move? e.g. any unintended axial movement or wobble? I assume the linear shafts correct this somewhat but was wondering what you've seen practically.

**Comment by mzbotreprap** [comment]
I had the screws contained at the top originally, which lead (no pun intended) to Z artifacts. You have to spend a lot more on the lead screws to have them be perfect. Removing the top constraints improved the print quality dramatically.

**Comment by quixotic120** [comment]
ah that makes sense. I may add something to mine to try it out - I'm using lead screws salvaged from an old CNC so they are pretty high quality. However, they're coupled to steppers so that may eliminate any benefit of quality. Thanks for the insight!
