### ISSUE TITLE
s/NAME/NEMA in BOM v1.05

### ISSUE THREAD

**Issue by dcousens** [mzbotreprap/VORON#28]

**Comment by mzbotreprap** [comment]
Auto-correct strikes again :)

**Comment by dcousens** [comment]
You should add the BOM as a markdown table,  then it'll be under source control.

**Comment by dcousens** [comment]
Or even just CSV

**Comment by dcousens** [comment]
Still exists

**Comment by mzbotreprap** [comment]
I'm using this as a reminder to move the BOM to MarkDown :) soooooooon...

**Comment by dcousens** [comment]
Haha, I knew it.
