### ISSUE TITLE
Grease Documentation

### ISSUE THREAD

**Issue by codexmas** [mzbotreprap/VORON#3]
Please consider adding a general recommendation for the grease that you use for packing the bearings.
Also, a description of how to pack them and with approximately how much so people don't end up with a gooey mess.

Docs are really coming along :)

**Comment by mzbotreprap** [comment]
Great suggestion.

Thanks! Writing a manual and getting the right illustrations has been the hardest part of the project.

**Comment by codexmas** [comment]
Great job so far, I am stoked to collect all the parts I don't have and get started on the build.

**Comment by codexmas** [comment]
Closing
