### ISSUE TITLE
"Z Sensor Mount : Wire Anchor [REV A].stp" filename causes issues on some platforms

### ISSUE THREAD

**Issue by nallar** [mzbotreprap/VORON#30]
Can't create a file with `:` in the name on Windows, so working with the repository on a windows machine is a pain.

**Comment by dcousens** [comment]
Probably should just avoid file names with spaces and special characters

**Comment by mzbotreprap** [comment]
This is gonna get fixed when I flatten out the STL folder. It's too fancy.

I'll go to a more OS agnostic file names.

**Comment by nallar** [comment]
That fixed the STL, but the STP still has a name with special characters: https://github.com/mzbotreprap/VORON/blob/416867d0a27b4f90c2b04ee9433b40fc8d030027/STEP/Gantry/X%20Carriage/Z%20Sensor%20Mount%20:%20Wire%20Anchor%20%5BREV%20A%5D.stp

**Comment by mzbotreprap** [comment]
Wow, you are quick. That's coming next :)

**Comment by mzbotreprap** [comment]
There you go. All clean and uniform. My inner OCD is getting better, I may even sleep now...
