### ISSUE TITLE
Page 51 of manual shows weird config for E3D v6

### ISSUE THREAD

**Issue by dgcaste** [mzbotreprap/VORON#31]
Was looking at the drawing on page 51 (per the page numbers on bottom, p.52 per Acrobat) and it shows the heater block sideways, showing square on XZ and short on Y. It's supposed to square on XY and short on Z. Looks like the same issue is there for the Chimera drawing. Pretty harmless since this just gives you more Z height potential but could be an issue with how you arranged the air duct or the payload holder. I'm guessing this is a vestige from your volcano setup with does have it arranged like that: https://cdn.shopify.com/s/files/1/0239/9287/products/C_v6-1.75-U-3-500x500_grande.jpg?v=1439852873

**Comment by mzbotreprap** [comment]
HA! That's not a v6, that's in fact a volcano :) Nice catch.

I'll fix this on the next iteration (gonna update the illustrations for showing the heater block config for v6 Chimera)

**Comment by dgcaste** [comment]
Word
