### ISSUE TITLE
Z Sensor Mount file downloads as 0 bytes every time

### ISSUE THREAD

**Issue by dgcaste** [mzbotreprap/VORON#32]
I tried downloading the whole repo as a zip or using git gui to clone the master to my computer, and Z sensor mount STL always downloads as a 0 byte size file that can't be deleted, while not even showing the true filename of the files that currently exist in git. Clicking on the individual STLs works though. Recommend renaming folder or something so bug disappears from git servers? See screenshot

http://prntscr.com/b95foe

**Comment by nallar** [comment]
You're running into the same problem as #30

**Comment by dgcaste** [comment]
Good call @nallar -- I'll close this
