### ISSUE TITLE
E3D Extruder Assembly Instructions

### ISSUE THREAD

**Issue by mschweiner** [mzbotreprap/VORON#33]
Consider linking to (or including, if permitted) the E3D assembly guide in §5.2 X Carriage Payload (p.51). The Chimera as ordered from Filastruder includes a prominent card instructing the buyer to refer immediately to these build instructions.

http://wiki.e3d-online.com/wiki/E3D-v6_Assembly
http://wiki.e3d-online.com/wiki/Cyclops_%26_Chimera_Assembly

With regard to the Chimera, Section 5.2 should also instruct the assembler to omit the kit-included Bowden collets designed for embedded use in the cold side. The larger included BSP couplers will instead be used by threading into the Voron part "Carriage Midsection (Chimera) Top BSP.stl".

Finally, the included M3 washers should be placed between the cold side and the Voron bottom carriage mount.

**Comment by mzbotreprap** [comment]
User can still use the included collets. The BSP option is for people who don't have them (Chinese Chimaras)

Also, why do you need M3 washers for mounting? Cold side has its name for a reason :)
