### ISSUE TITLE
BOM inconsistencies

### ISSUE THREAD

**Issue by franknitty69** [mzbotreprap/VORON#43]
the BOM updated 7/18/16 has a few inconsistencies.

linear motion
- NEMA 17 Linear Stepper has a typo in description

Electronics
- electronics has four NEMA 17 Steppers listed (2 line items)
- LCD Controller Full Graphics doesn't have a qty

Electronics (Optional)
- led strip is listed in Electronics and Electronics (optional)

Extrusion
- E3D Chimera Kit is listed in Electronics and Extrusion

**Comment by mzbotreprap** [comment]
Ok, I'm convinced. I'll approve your pull request. :)

... And fix the MarkDown BOM
