### ISSUE TITLE
Thermal Fuse for Heated bed

### ISSUE THREAD

**Issue by codexmas** [mzbotreprap/VORON#5]
As a safety precaution I am thinking of adding one of these for the AC silicone heating pad:
http://www.aliexpress.com/item/5-x-250V-10A-140-Celsius-NC-Normal-Close-Thermostat-Temperature-Thermal-Switch/2009867145.html

**Comment by mzbotreprap** [comment]
That's a fantastic idea! Saw it used on a Delta with a mains voltage bed, but kind of forgot about it.

I'll add it into the BOM as an option, and  include it in the manual (with full credits of course)

**Comment by codexmas** [comment]
Sweet as!
