### ISSUE TITLE
Locknut on extruder gear

### ISSUE THREAD

**Issue by gcormier** [mzbotreprap/VORON#51]
I've had a few failed prints due to the bolt coming loose. I've hit it with some Loctite carefull as it Loctite generally doesn't play well with plastics.... this should be a locknut.

**Comment by Scozz0** [comment]
Highly recommend going for the purple 'light' strength loctite/permatex.

**Comment by kmbecker13** [comment]
I had a similar issue with the nut coming off and then overtightened it to the point that i damaged the bearings in the extruder, definitely need to watch out for that.

**Comment by dgcaste** [comment]
Can confirm I've had similar issue, resolved with tightening but stresses bearing a bit. Loctite or a locknut here would make sense.

**Comment by gcormier** [comment]
Closing. Nut is supposed to have a second one afterwards.
