### ISSUE TITLE
Change to probe/fan holder

### ISSUE THREAD

**Issue by gcormier** [mzbotreprap/VORON#53]
The tab sticking upwards should be slightly wider, and have slightly more prominent cutouts for zipties. With all the cables ziptied, the radius is enough that the ziptie slides up easily enough.

**Comment by mzbotreprap** [comment]
That's a good idea in general, but really only the carriage harness end should be attached there. The other connections can be bundled and zip tied to themselves. I'm working on a better wire management system back there

**Comment by gcormier** [comment]
1.5 changes
