### ISSUE TITLE
Documentation : RAMPS Fan

### ISSUE THREAD

**Issue by gcormier** [mzbotreprap/VORON#55]
I am not sure how noob-friendly we want the kit docs.

I believe the RAMPS fan will turn itself off 60 seconds after the steppers are turned off. It would be nice to mention this in the manual ("This fan is controlled by RAMPS and may turn off when the printer is idle.")

I thought my fan was broken to be honest :)

If not, then just close the issue. Learnt my lesson.

**Comment by dgcaste** [comment]
Easier instructions = less need for support = better customer experience = less unnecessary negative reviews in the inevitable online marketplace = better visibility and rep = more sales

Having good documentation that works for all levels of users is critical to the success of a product. Documentation can never be too clear.
