### ISSUE TITLE
RAMPS Case Improvements

### ISSUE THREAD

**Issue by gcormier** [mzbotreprap/VORON#59]
I think the RAMPS case needs minor improvements.

1) I think the case itself should be slightly deeper. Cable management is impossible with this one. Given there's little value for unused space inside the perimeter, I printed one that's 3cm deeper. I'll see how it goes, but this should be plenty of space for wires, and also allow me to mount the fan inside the box.

2) The fan grill should be added to the lid. I have a CAD file of this I can send a pull request in soon. Leaving the spinning blades inside the ramps case is asking to have a wire mixed in with a moving fan blade at some point during the printer's operation.

3) Any/all fan grills should have some clearance from the grill and the mating surface. After a few heat cycles I found my fan started "ticking" as it touched one part of the fan guard ever so slightly. I'll also submit a pull request for this as well.

4) I'm not sure how, but better access to D8/D9/D10 to put the wires in would be a nice-to-have. It's certainly management right now with some cussing and fine maneuvering of needle nose pliers, but less than ideal.

(I'm also unsure how to manage any of the CAD stuff. I'm also Fusion360... but that might make community contributions difficult, as there's a single F3D file for VORON which might not make for very friendly editing of different parts by different users...)

**Comment by mzbotreprap** [comment]
Scheduled for V1.5 Phase 3
