### ISSUE TITLE
VORON/BOM/voron_germany.md 110v

### ISSUE THREAD

**Issue by McAdamous** [mzbotreprap/VORON#65]
VORON/BOM/voron_germany.md States 110v - incorrect voltage for EU/Germany

This could confuse people who are not so familiar...

**Comment by FHeilmann** [comment]
Thanks, I submitted a pull request.

**Comment by mzbotreprap** [comment]
Pull request has been merged. Can we close this?

**Comment by McAdamous** [comment]
It does not seem to have been merged - can you check again RCF?

**Comment by mzbotreprap** [comment]
Ah, true story. Helps if I actually merge the pull request.
