### ISSUE TITLE
V1.5 Final v6 carriage center spacing issue

### ISSUE THREAD

**Issue by FHeilmann** [mzbotreprap/VORON#71]
Just printed the final v6 carriage and I cannot insert the hotend without it touching/shorting the legs of my switch. My Plastik screws have a rather large head so they get in the way too. 

I like that the attempt to save space has been made, but I feel it may be a little too much in this case.

**Comment by mzbotreprap** [comment]
You're not alone in your concerns. I'm gonna fix it

**Comment by FHeilmann** [comment]
If you're talking about that one guy on reddit, thats also me ^^" Last time you asked me to open an issue on github so here it is.
