### ISSUE TITLE
Locating BOM 80mm/30mm fans

### ISSUE THREAD

**Issue by codexmas** [mzbotreprap/VORON#8]
While you have provided the width/height dimensions, the thickness is not.
Please provide your recommendation for the 80mm fan

**Comment by mzbotreprap** [comment]
80mm fan is for ramps enclosure and can be whatever width you desire. I think the standard (read: cheapest) is 80x80x25mm, but pretty much any 80mm with provide sufficient cooling. I'll update the BOM :)

30mm fan is not on the BOM anymore, replaced by the blower fan (which has the full specs)

**Comment by mzbotreprap** [comment]
BOM updated. Closing.
