### ISSUE TITLE
Suggestion for next rev: nut holders for V6 hot end mount

### ISSUE THREAD

**Issue by yonkiman** [mzbotreprap/VORON#87]
The only place I've found where nuts are not captured in some manner and it causes minor inconvenience when they fall out is in the V6 Hotend Mount.  My solution is to solder (melt) 2 thin wires over opposite sides of each nut to keep them in place.  I suspect you could come up with something slightly more elegant!

**Comment by mzbotreprap** [comment]
![screen shot 2017-04-01 at 11 42 29 am](https://cloud.githubusercontent.com/assets/15057541/24581458/a50f9950-16d0-11e7-82f2-c47816486ae5.png)

**Comment by yonkiman** [comment]
Exactly.
