### ISSUE TITLE
LM10 bearings

### ISSUE THREAD

**Issue by lufton** [mzbotreprap/VORON#91]
Are there any models for 10mm linear bearings? I expand my printed area to be 350×350mm and afraid my 8mm shafts wouldn't be a good idea to use.

**Comment by lufton** [comment]
Up

**Comment by mzbotreprap** [comment]
Nope, 10mm bearings are too large for the designed parts. Everything has to grow. 

Fusion360 files are available if you want to take a stab at making your own. 

Also check the sub-Reddit to see if someone already did this.

**Comment by lufton** [comment]
I just thought you'll make them better and faster as original designer. Can you do some effort to make them, please?

**Comment by Maglin** [comment]
can now find 10mm mods on this GitHub.
