### ISSUE TITLE
Belted Z Drive

### ISSUE THREAD

**Issue by Nuker** [mzbotreprap/VORON#92]
I've found the STL files for the belted Z drive in the experimental folder.
Is there any documentation or something like that (rudimentary?) and can this be used for Voron 1.5?

**Comment by Fulg** [comment]
If you haven't seen it already: https://www.reddit.com/r/voroncorexy/comments/4z95oq/updates_on_the_belted_z_drive/

**Comment by Maglin** [comment]
Not a supported option.  Hence experimental.
