### ISSUE TITLE
Wiring blower and ssr

### ISSUE THREAD

**Issue by lufton** [mzbotreprap/VORON#93]
According to your manual blower and hotend fan needs to be wired to fan extender. I wire them there but I couldn't make my blower fan spin. Also I don't have 3-pin connector on my RAMPS mentioned to connect ssr to. Then I realize that one of fan extender pins is ssr control pin and connect my ssr to it. Now I can't understand where to connect my blower fan.
![img_20170414_101659](https://cloud.githubusercontent.com/assets/2139755/25036429/71a1498e-20fc-11e7-8df4-172b44a6c345.jpg)

**Comment by Printeronimo** [comment]
You need to shift down the extender so that the top row of pins is accessible for the ssr. Then connect the blowers to the extender as ahown in the diagram.

**Comment by lufton** [comment]
Thanks a lot! You Judy saved me from headache!
