### ISSUE TITLE
Power Box wiring gauge is inadequate

### ISSUE THREAD

**Issue by superjamie** [mzbotreprap/VORON#98]
The design currently suggests to use 20G wire between AC and heatbed.

Assuming the stock 250W heater at 110V that's 2.3A

According to http://www.powerstream.com/Wire_Size.htm the size 20G is not sufficient to safely carry this amount of power.

It should be *at least* 18G and probably more like 14G to provide over a 100% safety margin.

Given that 350W heaters are commonly available and used, 12G would be a better choice.

Reference: https://www.reddit.com/r/voroncorexy/comments/6b6tj5/wiring_voron_power_box_question_regarding_power/

**Comment by mzbotreprap** [comment]
Those numbers are given for 1000ft. 

Use the calculator they provide and plug in the 20AWG, 2.3A, and 1ft of wire (standard on 9" bed). You end up with 0.04% voltage drop, which equates to fairly negligible power dissipation. You of course can upsize all the wiring, but for the purposes of safety, 20AWG is plenty.

**Comment by superjamie** [comment]
Fair enough, thanks for the correction.
